// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PodcastController from "./podcast_controller"
application.register("podcast", PodcastController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TomSelectPlaylistController from "./tom_select_playlist_controller"
application.register("tom-select-playlist", TomSelectPlaylistController)
